version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./assets/:/src/assets/
      - ./config/:/src/config/
      - ./deps/:/src/deps/
      - ./lib/:/src/lib/
      - ./mix.exs:/src/mix.exs
      - ./mix.lock:/src/mix.lock
      - ./priv/:/src/priv/
      - ./test/:/src/test/
    tty: true
    ports:
      - 4000:4000
    command: ["mix", "phx.server"]
    env_file:
        - blizzard.env

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379
