version: '3'

services:
  web:
    image: drpandemic/royale-with-cheese-web
    tty: true
    ports:
      - 4000:4000
    command: ["mix", "phx.server"]
    env_file:
        - blizzard.env
        - phx.env
        - .env

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379
