version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-arm
    tty: true
    ports:
      - 4000:4000
    command: ["mix", "phx.server"]
    env_file:
        - blizzard.env
        - phx.env
        - .env
    environment:
        - MIX_ENV=prod

  database:
    image: postgres:latest
    env_file:
        - .env
    ports:
      - 5432:5432

  redis:
    image: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
