version: '3'

services:
  web:
    image: drpandemic/royale-with-cheese-web
    tty: true
    ports:
      - 80:4000
    command: ["mix", "phx.server"]
    env_file:
      - blizzard.env
      - phx.env
      - .env
    environment:
      - MIX_ENV=prod

  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379

volumes:
  pgdata:
