version: '3'

services:
  edge:
    image: drpandemic/royale-with-cheese-edge
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_HOSTNAME=default

  web:
    image: drpandemic/royale-with-cheese-web
    tty: true
    command: ["mix", "phx.server"]
    env_file:
      - blizzard.env
      - phx.env
      - .env
    environment:
      - MIX_ENV=prod

  database:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"

volumes:
  pgdata:
