version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    tty: true
    ports:
      - 4000:4000
    command: ["mix", "phx.server"]
    env_file:
        - blizzard.env
        - phx.env
        - .env
    environment:
      - MIX_ENV=dev
      - POSTGRES_PASSWORD=password

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 2GB

  mongo:
    image: postgres:latest
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          memory: 12GB

  redis:
    image: redis
    ports:
      - 6379:6379
